Repository cert-manager/issuer-lib, pull requests merged in 2023-09, with the labels that each got.

#42 Cleanup issuer controller
  controllers/certificaterequest_controller_integration_test.go
  controllers/certificaterequest_controller_test.go
  controllers/certificatesigningrequest_controller_test.go
  controllers/combined_controller_integration_test.go
  controllers/issuer_controller.go
  controllers/issuer_controller_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#56 README: explain how logs are meant to be used
  README.md
Labels: dco-signoff: yes, lgtm, approved, size/S

#57 Cleanup the CertificateRequest and CertificateSigningRequest controllers
  README.md
  controllers/certificaterequest_controller.go
  controllers/certificaterequest_controller_integration_test.go
  controllers/certificaterequest_controller_test.go
  controllers/certificatesigningrequest_controller.go
  controllers/certificatesigningrequest_controller_test.go
  controllers/combined_controller_integration_test.go
  controllers/issuer_controller.go
  controllers/issuer_controller_test.go
Labels: dco-signoff: yes, lgtm, approved, size/L

#43 Unify the CertificateRequest + CertificateSigningRequest controllers
  controllers/certificaterequest_controller.go
  controllers/certificaterequest_controller_integration_test.go
  controllers/certificaterequest_controller_test.go
  controllers/certificatesigningrequest_controller.go
  controllers/certificatesigningrequest_controller_test.go
  controllers/combined_controller.go
  controllers/request_controller.go
  controllers/request_objecthelper.go
  controllers/request_objecthelper_certificaterequest.go
  controllers/request_objecthelper_certificatesigningrequest.go
  internal/ssaclient/patch.go
Labels: dco-signoff: yes, size/XXL, lgtm, approved

#65 Try grouping the dependabot upgrades
  .github/dependabot.yaml
Labels: dco-signoff: yes, lgtm, approved

#55 Upgrade all dependencies
  api/v1alpha1/zz_generated.deepcopy.go
  go.mod
  go.sum
  internal/testsetups/simple/api/zz_generated.deepcopy.go
  internal/testsetups/simple/deploy/crds/testing.cert-manager.io_simpleclusterissuers.yaml
  internal/testsetups/simple/deploy/crds/testing.cert-manager.io_simpleissuers.yaml
  make/e2e-setup.mk
  make/image-preload.mk
  make/test.mk
  make/tools.mk
Labels: dco-signoff: yes, size/M, lgtm, approved
